
LOAD CSV WITH HEADERS FROM 'file:///<CSVFILE>' AS line
FIELDTERMINATOR '<FS>'
MERGE (s:<NODETYPE> {<unique_property>: line.<UNIQUE_PROPERTY>})
ON CREATE SET <SET_PROPERTIES>
ON MATCH SET <SET_PROPERTIES> ;

